---
title: "Final_Project"
author: "Rachel Bittner"
format: 
  html:
    self-contained: true
output-file: index.html
output-dir: docs
editor: visual
---

## GitHub Repo:

https://github.com/bittnation/ENVS_193DS_Final

```{r packages-read}

library(tidyverse)
library(janitor)
library(ggplot2)
library(dplyr)
# reading in basic packages


# read in data sets
```

# Problem 1. Research Writing

a. 

In part 1, they used Pearson's correlation. The key word "correlation" suggest that they either performed a Pearson's correlation test or Spearman's rho. Since kg year-1 and km are both continuous variables instead of rankings it is likely Pearson's r. 
 

In part 2, they used a one-way ANOVA. The key phrase "difference in average" indicates ANOVA which aims to compare the means (averages) of more than one group. The type of ANOVA was determined by the number of groups, the results indicated the comparison of more than three groups which requires a one-way ANOVA. 


b. 

To add more context to the results, my coworker should provide a Tukey's Honestly significant Difference and key ANOVA statistics. 

It is important to include Tukey's HSD because it provides context as to which of the 6 groups were actually different from each other. This is test is important because it prevents Type I errors.


Include key ANOVA statistics such as test type, F-value, degrees of freedom, and significance level to strengthen the statistical results. It aids readers ability to interpret data and draw conclusions and it promotes transparency and reduces skeptical (fix tense), the p-value doesn't tell the whole story so it is important to communicate all statistical results. 

c. 
ANOVA statistics: 
We found that there was a significant difference in average nitrogen load (kg year-1) between sources (urban land, atmospheric deposition, fertilizer, waste water treatment, and grasslands) (one-way ANOVa, F(df among groups, df withing groups),p = 0.02, a = significance level).

Tukey's HSD:
On Average, urban land tended to have [higher or lower] nitrogen loads (kg year-1) than grasslands ( _ kg year-1 (higher or lower), _ % CI: [x:y] kg year-1) and fertilizer (_ kg year-1 (higher or lower), _ % CI: [x:y] kg year-1 )...


# Problem 2. Research Writing

# Problem 3. Data Visualization

# Problem 4. Affective and Exploratopry Visualizations




